# CrossBow Docker image based on Huawei ModelArts CUDA 9
# ModelArts example: https://github.com/huawei-clouds/modelarts-example/blob/master/CustomImage
FROM swr.cn-north-1.myhuaweicloud.com/eiwizard/custom-gpu-cuda9-inner-moxing-cp36:1.1 as base

# Crossbow
ENV CROSSBOW_HOME /crossbow
RUN git clone --progress http://github.com/lsds/Crossbow.git crossbow \
    && cd crossbow \
    && mvn package \
    && cd clib-multigpu \
    && ./genmakefile.sh \
    && make -j $(nproc) \
    && cd ../ \
    && ./scripts/build.sh