# CrossBow Docker image based on Huawei ModelArts CUDA 9
# ModelArts example: https://github.com/huawei-clouds/modelarts-example/blob/master/CustomImage
FROM swr.cn-north-1.myhuaweicloud.com/eiwizard/custom-gpu-cuda9-cudnn72:1.0-0 as base

# See http://bugs.python.org/issue19846
ENV LANG C.UTF-8

RUN apt update && apt install -y --no-install-recommends \
        libfreetype6-dev \
        libhdf5-serial-dev \
        libpng12-dev \
        libzmq3-dev \
        pkg-config \
        software-properties-common \
        unzip \
        git \
        wget \
        openjdk-8-jdk \
        maven \
        libboost-all-dev \
        graphviz \
        cmake \
        nasm \
        && rm -rf /var/lib/apt/lists/*