# CrossBow Docker image based on Huawei ModelArts CUDA 9
# ModelArts example: https://github.com/huawei-clouds/modelarts-example/blob/master/CustomImage
FROM swr.cn-north-1.myhuaweicloud.com/eiwizard/custom-gpu-cuda9-cudnn72:1.0-2 as base

ENV BLAS_HOME /opt/OpenBLAS
ENV LD_LIBRARY_PATH $BLAS_HOME/lib:$LD_LIBRARY_PATH

ENV JPEG_HOME /libjpeg-turbo
ENV LD_LIBRARY_PATH $JPEG_HOME/lib:$LD_LIBRARY_PATH
ENV LD_LIBRARY_PATH $JPEG_HOME:$LD_LIBRARY_PATH

# Crossbow
ENV CROSSBOW_HOME /crossbow
RUN git clone --progress http://github.com/lsds/Crossbow.git crossbow \
    && cd crossbow \
    && ldconfig \
    && mvn package \
    && cd clib-multigpu \
    && ./genmakefile.sh \
    && make -j $(nproc) \
    && cd ../ \
    && ./scripts/build.sh

# Install tensorflow-gpu 1.12.0 in the conda environment (pip has been redirected to conda pip)
RUN pip install -i https://pypi.tuna.tsinghua.edu.cn/simple tensorflow-gpu==1.12.0 # Run this if in the mainland China
# RUN pip install tensorflow-gpu==1.12.0

WORKDIR /