/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class uk_ac_imperial_lsds_crossbow_device_blas_BLAS */

#ifndef _Included_uk_ac_imperial_lsds_crossbow_device_blas_BLAS
#define _Included_uk_ac_imperial_lsds_crossbow_device_blas_BLAS
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     uk_ac_imperial_lsds_crossbow_device_blas_BLAS
 * Method:    init
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_uk_ac_imperial_lsds_crossbow_device_blas_BLAS_init
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     uk_ac_imperial_lsds_crossbow_device_blas_BLAS
 * Method:    destroy
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_uk_ac_imperial_lsds_crossbow_device_blas_BLAS_destroy
  (JNIEnv *, jobject);

/*
 * Class:     uk_ac_imperial_lsds_crossbow_device_blas_BLAS
 * Method:    csgemm
 * Signature: (Ljava/lang/String;Ljava/lang/String;IIIFIIIIFII)I
 */
JNIEXPORT jint JNICALL Java_uk_ac_imperial_lsds_crossbow_device_blas_BLAS_csgemm__Ljava_lang_String_2Ljava_lang_String_2IIIFIIIIFII
  (JNIEnv *, jobject, jstring, jstring, jint, jint, jint, jfloat, jint, jint, jint, jint, jfloat, jint, jint);

/*
 * Class:     uk_ac_imperial_lsds_crossbow_device_blas_BLAS
 * Method:    csgemm
 * Signature: (Ljava/lang/String;Ljava/lang/String;IIIFLuk/ac/imperial/lsds/crossbow/data/IDataBuffer;IIILuk/ac/imperial/lsds/crossbow/data/IDataBuffer;IIIFLuk/ac/imperial/lsds/crossbow/data/IDataBuffer;III)I
 */
JNIEXPORT jint JNICALL Java_uk_ac_imperial_lsds_crossbow_device_blas_BLAS_csgemm__Ljava_lang_String_2Ljava_lang_String_2IIIFLuk_ac_imperial_lsds_crossbow_data_IDataBuffer_2IIILuk_ac_imperial_lsds_crossbow_data_IDataBuffer_2IIIFLuk_ac_imperial_lsds_crossbow_data_IDataBuffer_2III
  (JNIEnv *, jobject, jstring, jstring, jint, jint, jint, jfloat, jobject, jint, jint, jint, jobject, jint, jint, jint, jfloat, jobject, jint, jint, jint);

/*
 * Class:     uk_ac_imperial_lsds_crossbow_device_blas_BLAS
 * Method:    csgemv
 * Signature: (Ljava/lang/String;IIFIIIIFII)I
 */
JNIEXPORT jint JNICALL Java_uk_ac_imperial_lsds_crossbow_device_blas_BLAS_csgemv__Ljava_lang_String_2IIFIIIIFII
  (JNIEnv *, jobject, jstring, jint, jint, jfloat, jint, jint, jint, jint, jfloat, jint, jint);

/*
 * Class:     uk_ac_imperial_lsds_crossbow_device_blas_BLAS
 * Method:    csgemv
 * Signature: (Ljava/lang/String;IIFLuk/ac/imperial/lsds/crossbow/data/IDataBuffer;IIILuk/ac/imperial/lsds/crossbow/data/IDataBuffer;IFLuk/ac/imperial/lsds/crossbow/data/IDataBuffer;I)I
 */
JNIEXPORT jint JNICALL Java_uk_ac_imperial_lsds_crossbow_device_blas_BLAS_csgemv__Ljava_lang_String_2IIFLuk_ac_imperial_lsds_crossbow_data_IDataBuffer_2IIILuk_ac_imperial_lsds_crossbow_data_IDataBuffer_2IFLuk_ac_imperial_lsds_crossbow_data_IDataBuffer_2I
  (JNIEnv *, jobject, jstring, jint, jint, jfloat, jobject, jint, jint, jint, jobject, jint, jfloat, jobject, jint);

/*
 * Class:     uk_ac_imperial_lsds_crossbow_device_blas_BLAS
 * Method:    csaxpby
 * Signature: (IFIIFII)I
 */
JNIEXPORT jint JNICALL Java_uk_ac_imperial_lsds_crossbow_device_blas_BLAS_csaxpby__IFIIFII
  (JNIEnv *, jobject, jint, jfloat, jint, jint, jfloat, jint, jint);

/*
 * Class:     uk_ac_imperial_lsds_crossbow_device_blas_BLAS
 * Method:    csaxpby
 * Signature: (IFLuk/ac/imperial/lsds/crossbow/data/IDataBuffer;IIIFLuk/ac/imperial/lsds/crossbow/data/IDataBuffer;I)I
 */
JNIEXPORT jint JNICALL Java_uk_ac_imperial_lsds_crossbow_device_blas_BLAS_csaxpby__IFLuk_ac_imperial_lsds_crossbow_data_IDataBuffer_2IIIFLuk_ac_imperial_lsds_crossbow_data_IDataBuffer_2I
  (JNIEnv *, jobject, jint, jfloat, jobject, jint, jint, jint, jfloat, jobject, jint);

#ifdef __cplusplus
}
#endif
#endif
