/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class uk_ac_imperial_lsds_crossbow_device_ObjectRef */

#ifndef _Included_uk_ac_imperial_lsds_crossbow_device_ObjectRef
#define _Included_uk_ac_imperial_lsds_crossbow_device_ObjectRef
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     uk_ac_imperial_lsds_crossbow_device_ObjectRef
 * Method:    create
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_uk_ac_imperial_lsds_crossbow_device_ObjectRef_create
  (JNIEnv *, jobject, jint);

/*
 * Class:     uk_ac_imperial_lsds_crossbow_device_ObjectRef
 * Method:    get
 * Signature: ()Ljava/lang/Integer;
 */
JNIEXPORT jobject JNICALL Java_uk_ac_imperial_lsds_crossbow_device_ObjectRef_get
  (JNIEnv *, jobject);

/*
 * Class:     uk_ac_imperial_lsds_crossbow_device_ObjectRef
 * Method:    test
 * Signature: (Ljava/lang/Integer;)I
 */
JNIEXPORT jint JNICALL Java_uk_ac_imperial_lsds_crossbow_device_ObjectRef_test
  (JNIEnv *, jobject, jobject);

/*
 * Class:     uk_ac_imperial_lsds_crossbow_device_ObjectRef
 * Method:    testAndGet
 * Signature: (Ljava/lang/Integer;)Ljava/lang/Integer;
 */
JNIEXPORT jobject JNICALL Java_uk_ac_imperial_lsds_crossbow_device_ObjectRef_testAndGet
  (JNIEnv *, jobject, jobject);

#ifdef __cplusplus
}
#endif
#endif
